# fly.toml app configuration file generated for miaphan on 2023-09-07T02:02:18Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "miaphan"
primary_region = "syd"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[http_service]
internal_port = 8043
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 200

[experimental]
cmd = ["-fallback", "./index.html"]
